# Generated by Django 5.0 on 2023-12-06 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentsComputer",
            fields=[
                ("Com_ID_num", models.AutoField(primary_key=True, serialize=False)),
                ("RAM", models.CharField(max_length=300)),
                ("MEM", models.CharField(max_length=300, null=True)),
                ("CPU", models.CharField(max_length=300)),
                ("GPU", models.CharField(max_length=300)),
                ("PSU", models.CharField(max_length=300)),
                ("MOBO", models.CharField(max_length=300)),
                (
                    "PC_Photo",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "nickname",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="p_computer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Computers",
            },
        ),
    ]
