# Generated by Django 4.1.1 on 2023-10-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "nickname",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("mail", models.EmailField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=20)),
                ("surname", models.CharField(max_length=20)),
                ("password", models.CharField(max_length=200)),
                ("gender", models.CharField(max_length=1)),
                ("bornDate", models.DateField()),
                ("descr", models.CharField(max_length=500)),
            ],
        ),
    ]
