# Generated by Django 4.2.6 on 2023-10-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounts",
            name="bornDate",
        ),
        migrations.RemoveField(
            model_name="accounts",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="accounts",
            name="name",
        ),
        migrations.RemoveField(
            model_name="accounts",
            name="surname",
        ),
    ]
